#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  # WIZARD_NO_CLEAR=1 keeps every stage in the scrollback, so a mis-click that
  # skips a prompt can be recovered by scrolling up instead of re-running.
  [[ -z "${WIZARD_NO_CLEAR:-}" ]] || { printf '
'; return 0; }
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  # Print the URL on its own bare line: long links survive terminal wrapping
  # intact, so they stay selectable and clickable.
  printf '  %s↗ open this link:%s

' "$GREEN" "$RESET"
  printf '%s

' "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    fi
  } >/dev/null 2>&1 || true
}

# pause "msg" — wait for the human to confirm they've done the manual part.
# _TTY — the terminal to read from. Falls back to stdin when /dev/tty is
# unavailable. Without this, a shell launched from PowerShell gets a stdin that
# is already at EOF, so every prompt returns instantly and the wizard races
# through all its stages without ever waiting for the human.
if { : < /dev/tty; } 2>/dev/null; then _TTY=/dev/tty; else _TTY=/dev/stdin; fi

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ < "$_TTY" || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply < "$_TTY" || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input < "$_TTY" || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input < "$_TTY" || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  set +e
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Keep captured values beside the guide rather than in the repo root.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.report.env"

PROJECT_ID="ecommerceapp-auth-db-cleana"
DATASET="sales_analytics"
STORE_ID="${STORE_ID:-buybuy}"

BOOTSTRAP_URL="https://lookerstudio.google.com/reporting/create?c.mode=edit&r.reportName=Store%20Analytics&ds.connector=bigQuery&ds.type=TABLE&ds.projectId=${PROJECT_ID}&ds.datasetId=${DATASET}&ds.tableId=v_orders&ds.datasourceName=Orders"

banner "LojaPronta — build the store analytics report"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Bootstrap the report"
say "Looker Studio has no create-a-report API, so the build is manual."
say "This link creates the report with v_orders already wired as 'Orders'."
open_url "$BOOTSTRAP_URL"
step "If prompted, authorize the BigQuery connection — approve it."
step "You should land in edit mode on a report named 'Store Analytics'."
note "Use this alias-less ds. link, not the ds.ds0. form — the aliased variant"
note "fails on a blank create with 'ds0 is not a valid data source alias'."
warn "If the link misbehaves: lookerstudio.google.com -> Create -> Report ->"
warn "BigQuery -> ${PROJECT_ID} -> ${DATASET} -> v_orders -> Add."
pause "Report open in edit mode?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Add the second data source (line items)"
say "The product tiles read line-item grain, which the bootstrap link cannot wire."
step "Resource -> Manage added data sources -> Add a data source -> BigQuery"
step "Project ${PROJECT_ID} -> dataset ${DATASET} -> table v_line_items -> Add"
step "Name it 'Line items' so the chart recipes below match."
pause "Both 'Orders' and 'Line items' listed as data sources?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Date range control"
say "One control drives every chart that has a date dimension."
step "Insert -> Date range control; drop it at the top of the canvas."
step "Confirm its date dimension is order_date."
step "Set a default range that covers the seeded data (last 90 days is safe)."
note "Seeded orders currently span roughly 21 Jun 2026 -> 13 Aug 2026."
pause "Date range control placed?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Two calculated fields"
say "Two tiles need fields that do not exist in the views."
step "Resource -> Manage added data sources -> Orders -> Edit -> Add a field"
step "Name: AOV             Formula: SUM(revenue)/COUNT(order_id)"
step "Name: Discount rate   Formula: SUM(discount)/NULLIF(SUM(gross),0)"
step "Set 'Discount rate' type to Percent, then Done -> Close."
pause "Both fields saved on the Orders source?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Section 1 — Executive KPIs + revenue trend (5 tiles)"
say "Insert each tile, then set its source / dimension / metric:"
step "Scorecard   · Orders     · metric SUM(revenue)       -> 'Total revenue'"
step "Scorecard   · Orders     · metric Count of order_id  -> 'Orders'"
step "Scorecard   · Orders     · metric AOV                -> 'Avg order value'"
step "Scorecard   · Line items · metric SUM(quantity)      -> 'Units sold'"
step "Time series · Orders     · dim order_date, metric SUM(revenue)"
note "Expect roughly 25,191 in revenue across 30 orders on the seeded data."
pause "Section 1 done?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Section 2 — Product & category (3 tiles)"
step "Table · Line items · dim title; metrics SUM(line_revenue), SUM(quantity)"
step "      sort by line_revenue descending -> 'Top products'"
step "Bar   · Line items · dim category_name, metric SUM(line_revenue)"
step "Bar   · Line items · dim color, metric SUM(quantity)"
note "All six categories carry units, so none of these should render empty."
pause "Section 2 done?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Section 3 — Payment & discounts (4 tiles)"
step "Pie       · Orders · dim payment_method, metric SUM(revenue)"
step "Bar       · Orders · dim installments,   metric Count of order_id"
step "Scorecard · Orders · metric Discount rate (format as percent)"
step "Scorecard · Orders · metric SUM(freight)"
note "Seeded data has three payment methods: credit_card, pix, boleto."
pause "Section 3 done?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Section 4 — Customer breakdown (3 tiles)"
warn "Product call: this section shows demographics to every store owner."
warn "The views expose only aggregate gender / age band and a hashed user_key,"
warn "never a name or raw id — but you may still prefer to drop the section."
if confirm "Build the customer breakdown section?"; then
  step "Pie · Orders · dim user_gender,  metric SUM(revenue)"
  step "Bar · Orders · dim age_band,     metric Count of order_id"
  step "Bar · Orders · dim is_returning, metric COUNT_DISTINCT(user_key)"
  pause "Section 4 done?"
else
  SKIPPED+=("Customer breakdown section (skipped by choice)")
  note "Skipped — the report will have ~12 tiles instead of ~15."
  pause "Continuing."
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Custom-query sources so @storeId filters the report"
say "The admin embeds the report with ?params={\"storeId\":\"<id>\"}."
say "For that to filter anything, the sources must accept a storeId parameter."
step "Resource -> Manage added data sources -> Add a data source -> BigQuery"
step "-> Custom query -> billing project ${PROJECT_ID}. Paste:"
printf '\n      %sSELECT * FROM `%s.%s.v_orders`%s\n' "$DIM" "$PROJECT_ID" "$DATASET" "$RESET"
printf '      %sWHERE store_id = @storeId%s\n\n' "$DIM" "$RESET"
step "Looker Studio detects @storeId. Set its default value to: ${STORE_ID}"
step "Tick \"Allow 'storeId' to be modified in reports\", then Add."
step "Repeat for v_line_items with the same WHERE clause."
warn "The parameter must be named exactly storeId — the app depends on it."
pause "Both custom-query sources added?"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Repoint every chart at the custom-query sources"
say "The tiles still point at the plain tables; move them across."
step "Select each chart -> right panel -> Data source -> switch to the"
step "matching custom-query source (order tiles -> the v_orders query,"
step "product tiles -> the v_line_items query)."
step "Check every tile still renders after switching."
note "Miss one and that tile will quietly ignore the store filter."
pause "All charts repointed?"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Enable embedding"
step "File -> Embed report -> tick 'Enable embedding'."
step "Copy the embed URL (or the share URL set to 'anyone with the link can view')."
ask LOOKER_EMBED_URL "Paste the embed URL:"
if [[ -z "${LOOKER_EMBED_URL:-}" ]]; then
  warn "No URL captured — re-run this wizard once you have it."
  SKIPPED+=("Looker embed URL (re-run the wizard)")
else
  write_env LOOKER_EMBED_URL "$LOOKER_EMBED_URL"
fi
pause "Continuing."

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Wire the URL into the store"
if [[ -z "${LOOKER_EMBED_URL:-}" ]]; then
  note "Skipped — no embed URL was captured."
elif confirm "Write branding.lookerEmbedUrl to stores/${STORE_ID} for you?"; then
  say "Patching Firestore via the REST API with your gcloud credentials..."
  _token=$(gcloud auth print-access-token 2>/dev/null || true)
  if [[ -z "$_token" ]]; then
    warn "gcloud has no active login — use the admin UI instead."
    SKIPPED+=("Paste embed URL into admin Settings -> Analytics dashboard")
  else
    _api="https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/stores/${STORE_ID}?updateMask.fieldPaths=branding.lookerEmbedUrl"
    _body="{\"fields\":{\"branding\":{\"mapValue\":{\"fields\":{\"lookerEmbedUrl\":{\"stringValue\":\"${LOOKER_EMBED_URL}\"}}}}}}"
    _out=$(mktemp)
    _code=$(curl -s -o "$_out" -w '%{http_code}' -X PATCH "$_api" \
      -H "Authorization: Bearer ${_token}" \
      -H "Content-Type: application/json" -d "$_body")
    if [[ "$_code" == "200" ]]; then
      printf '  %s✓ wrote%s branding.lookerEmbedUrl to stores/%s\n' "$GREEN" "$RESET" "$STORE_ID"
    else
      warn "Firestore returned HTTP ${_code} — falling back to the admin UI."
      note "$(head -c 300 "$_out" 2>/dev/null || true)"
      SKIPPED+=("Paste embed URL into admin Settings -> Analytics dashboard")
    fi
    rm -f "$_out"
  fi
else
  step "In the store admin: Settings -> Analytics dashboard"
  step "Paste the URL into 'Dashboard embed URL', then Save."
fi
say ""
step "Now open the admin Dashboard page — the report should render in place"
step "of the empty state. That view is screenshot #6 for the case study."
pause "Dashboard rendering the report?"

finish
