// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVMTAj_YV0rwv5eK7aSAoY8hEW6PJavwY',
    appId: '1:502375403738:web:41119525f89ca66eba15e3',
    messagingSenderId: '502375403738',
    projectId: 'ecommerceapp-auth-db-cleana',
    authDomain: 'ecommerceapp-auth-db-cleana.firebaseapp.com',
    storageBucket: 'ecommerceapp-auth-db-cleana.firebasestorage.app',
    measurementId: 'G-98J1E4VXR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUj8jCCAlCG84pBC6q_1u_vKPFeWePRI',
    appId: '1:502375403738:android:6bfa6cf220acdf4aba15e3',
    messagingSenderId: '502375403738',
    projectId: 'ecommerceapp-auth-db-cleana',
    storageBucket: 'ecommerceapp-auth-db-cleana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHEcKth4SFKpElFUWdOiJbUORzD6e3H4Q',
    appId: '1:502375403738:ios:9b0187458eeac717ba15e3',
    messagingSenderId: '502375403738',
    projectId: 'ecommerceapp-auth-db-cleana',
    storageBucket: 'ecommerceapp-auth-db-cleana.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppWithFirebaseBlocCleanArchitecture',
  );
}
